### ISSUE TITLE
CPU device leaks slang session.

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang-rhi#53] opened 2024-09-26 01:04 UTC
When slang-test uses cpu device, the slang session isn't properly released.

To reproduce, run `slang-test` with this arguments:
```
slang-test tests/compute/constant-buffer-memory-packing -api cpu
```

This currently triggers an assert in debug that the reference count of the slang session doesn't go to 0.

**Comment by skallweitNV** [comment] 2024-09-27 12:51
Ok, this was actually caused by a change I made. Fixed now.

**Closed** 2024-09-27 12:55 UTC
